package sv.avantia.depurador.agregadores.utileria;

/**
 * enum para manejar los codigos de Error evitando que se repitan y de esta
 * forma llevo mayor control y mayor orden y un acceso rapido para conocer la
 * descripcion del error segun el codigo
 * 
 * @author Emejia - Avantia Consultores
 * @version 0.1
 * */
public enum ErroresSDA {

	EJECUCION_EXITOSA(3000),
	
	// error generico por problemas no manejada dentro de la aplicacion
	ERROR_GENERICO(4000),
	ERROR_GENERICO_BAJA_MASIVA(4001),
	ERROR_GENERICO_BAJA_ARCHIVO(4002),
	ERROR_GENERICO_BAJA_UNITARIA(4003),
	ERROR_GENERICO_BAJA_WEBSERVICES(4004),
	ERROR_GENERICO_ALTA_WEBSERVICES(4005),
	ERROR_AL_OBTENER_EL_INSUMO_NUMEROS(4006),
	ERROR_PASANDO_SOAPMESSAGE_RESPONSE_A_DOCUMENT(4007),
	ERROR_PASANDO_DOCUMENT_A_CADENA_TEXTO(4008),
	ERROR_AL_LEER_LA_RESPUESTA_OBTENIDA_DEL_METODO_POR_ASMX(4009),
	ERROR_OBTENIDO_EN_LA_RESPUESTA_DEL_METODO_POR_ASMX_CODE_ERROR(4010),
	ERROR_EL_CONSULTAR_TIMEUP_EN_EL_METODO_A_TRAVES_DE_ASMX(4011),
	ERROR_TIMEUP_EXCEPTION(4012),
	ERROR_AL_INVOCAR_EL_METODO_A_TRAVES_DE_ASMX(4013),
	ERROR_AL_INYECTAR_MENSAJE_ENVIO_POR_ASMX(4014),
	ERROR_AL_INVOCAR_EL_METODO_SIN_SEGURIDAD(4015),
	ERROR_PASANDO_DE_CADENA_TEXTO_A_DOCUMENT(4016),
	ERROR_AL_CREAR_SOAP_CLIENT(4017),
	ERROR_AL_CREAR_ENDPOINT_CON_EL_INSUMO_OBTENIDO(4018),
	ERROR_AL_CONSULTAR_TIMEUP_EN_EL_METODO_SIN_SEGURIDAD(4019),
	ERROR_CREANDO_CONEXION_HTTPS(4020),
	ERROR_AL_INVOCAR_EL_METODO_CON_SEGURIDAD(4021),
	ERROR_AL_CONSULTAR_TIMEUP_EN_EL_METODO_CON_SEGURIDAD(4022),
	ERROR_AL_CREAR_CONEXION_FACTORY_HTTPS(4023),
	ERROR_AL_INYECTAR_MENSAJE_ENVIO_EN_EL_METODO_CON_SEGURIDAD(4024),
	ERROR_AL_VERIFICAR_LOS_CERTIFICADOS_DE_SEGURIDAD(4025),
	ERROR_NULLPOINTEREXCEPTION(4026),
	ERROR_DESCRITO_DENTRO_DEL_MENSAJE_RECIBIDO(4027),
	ERROR_AL_LLENAR_LOS_PARAMETROS_DE_COMUNICACION_CON_LOS_AGREGADORES(4028),
	
	NO_SE_ENCONTRO_EL_VALOR_PARAMETRIZADO_DENTRO_DE_LA_RESPUESTA_RECIBIDA(5000),
	SIN_SERVICIOS_ACTIVOS(5001);

	private int value;

	private ErroresSDA(int value) {
		this.value = value;
	}

	public int getCodigo() {
		return value;
	}

	public String getDescripcion() {
		return this.name().replaceAll("_", " ");
	}
}
